"""create collaboration tables

Revision ID: REPLACE_THIS
Revises: c1a7dc670b27
Create Date: 2026-09-21
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# IMPORTANT:
# Replace this with the Revision ID generated by Alembic
# if your generated filename contains a different ID.

revision: str = "47fb4174"
down_revision: Union[str, Sequence[str], None] = "c1a7dc670b27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "collaboration_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "started_by",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "ended_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_collaboration_sessions_started_by",
        "collaboration_sessions",
        ["started_by"],
    )

    op.create_table(
        "collaboration_participants",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "employee_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "permission",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "left_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["collaboration_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_collaboration_participants_session_id",
        "collaboration_participants",
        ["session_id"],
    )

    op.create_index(
        "ix_collaboration_participants_employee_id",
        "collaboration_participants",
        ["employee_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_collaboration_participants_employee_id",
        table_name="collaboration_participants",
    )

    op.drop_index(
        "ix_collaboration_participants_session_id",
        table_name="collaboration_participants",
    )

    op.drop_table("collaboration_participants")

    op.drop_index(
        "ix_collaboration_sessions_started_by",
        table_name="collaboration_sessions",
    )

    op.drop_table("collaboration_sessions")